### PR TITLE
Background docs updates

### PR DESCRIPTION
**Pull request by AcademyInPeril**
Updated relative links, solving issue #26. Renamed some legacy references to the Transit Network name, and updated CONTRIBUTORS.md (albeit in a fashion that will need further updates).

### CODE REVIEW

**Comment by vkoves** [comment]
@AcademyInPeril - since docs can be viewed in a variety of places (through a PR, on a branch, etc.) I'd actually advise against using relative links. Instead, I'd using link definitions at the end of the markdown file so that they are all in one place and can be changed easily. See [markdown links documentation], or a quick example:

```markdown
Some [link text][link-name]

[link-name]: http://link-path.com
```

**Comment by vkoves** [comment]
@AcademyInPeril - what is the state of this PR?

**Comment by AcademyInPeril** [comment]
Apologies for the delay. Does having these definitions at the bottom address the problem of absolute pathing in forks/clones?

**Comment by vkoves** [comment]
Apologies, I realize I wasn't super clear on that. I'd suggest switching to absolute links (which fixes the issue) and then putting link references at the bottom to make that more maintainable

**Comment by AcademyInPeril** [comment]
I agree that seems to be the best compromise to strike in order to make forking as easy as possible. Let me know if you see any relative links I've missed.

**Comment by vkoves** [comment]
Also pro-top @AcademyInPeril, if you simply say resolves #22 in your PR description, that'll auto close the issue when the PR is merged. See the [GitHub docs](https://help.github.com/articles/closing-issues-using-keywords/).

**Pull request merged**
