### PR TITLE
Flexbox2

### PR DESCRIPTION
**Pull request by fairbco**
header fully converted to desktop. signed in/signed out version for both mobile and desktop finished.

### CODE REVIEW

**Comment by fairbco** [comment]
don't consider this branch just yet. I had to pull the search bar back in and I lost functionality, nothing on click. I'll comment when this quirk is fixed and reach out for a review.

**Comment by fairbco** [comment]
Fixed it! Good to go! let me know if there is anything to fix before this pull request is approved. thank you!

**Comment by vkoves** [comment]
On first glance this looks pretty good - the desktop and header both look solid. However, I've noticed two issues:

All text colors have changed from grey (`#535353`) to black. Take a look at the [live site](http://transit-network.herokuapp.com/) and compare the homepage text to see what I mean.

The second issue is that there seem to be some overlap issues when you open up the mobile menu. Here's a screenshot of the menu when open using the mobile inspector:

screenshot from 2017-10-03 19-45-02

I assume that's an issue with the `z-index` not being high enough or the positioning.

**Comment by vkoves** [comment]
This pull request has been stale for a while, so I am going to close it. If folks would like to work on it, feel free to add commits on the branch and reopen the PR. If there's nothing on the branch in a month or so, we can consider deleting it to clean up the GitHub.

**Pull request closed without merging**
