### PR TITLE
Add feature to sort all lines page DOM by id or name

### LINKED ISSUE #42: Lines Should be Sortable Via ID or Name
This issue is particularly visible on the CTA, which has bus numbers and bus names. You should be able to sort by either.

Original report from UX review last week:
> Bus menu should have the option to sort by alpha or numeric

### PR DESCRIPTION
**Pull request by Edwin-F**
I would like to resolve #42 . 
This uses jquery and javascript methods to sort the all lines pages by either line id or line name. I added two buttons on the all-lines page. 
@vkoves  Let me know if you want additional changes. Thanks!

### CODE REVIEW

**Comment by vkoves** [comment]
@Edwin-F - sorry for not getting to this earlier. I'm going to review this later tonight, but can you start by double checking your indentation? I don't think we've specified an explicit Caravan preference for indents, but looking at the files in GitHub's code preview it seems that your indentation isn't consistent with our files in both the HTML and the JS. I'll add more thorough comments later tonight, but let me know if you have any specific questions/concerns.

**Comment by Edwin-F** [comment]
I think I fixed the indents. On my side, I'm using sublime text editor and forgot that I had settings that made tabs/indents be viewed as spaces. Originally, everything on my side looked indented correctly and didn't realized this changed on github. I changed the settings on my sublime editor.

**Comment by Edwin-F** [comment]
@vkoves Thanks for the feedback. 

1. I chose JS since at the time I thought it wouldn't be necessary to send another http request to the backend to get the data sorted after the fact that the data is already in front of the user. Initially, I noticed it took awhile to render all the lines in the initial request, and assumed js might be faster since I didn't have to wait for the backend to rerender the items again. 
I checked that the code works with chrome developer tools on the heroku site and also tested on my local repo. I can look into incorporating actual tests at a later date.

2. Although I'm rusty at the moment, I have used before Cabybara with Rspec to test front-end elements, so this might one possibility. Also, we could use of Selenium to test front-end stuff (although I have no experience with it yet, but I can give it a try).

We could also write the functionality in ruby, and track compare the time it takes to sort items by a) using js on the front-end b) using ruby on the back-end, and choose the one that has the shortest amt of time. But I can see it might be concerning if in the future, someone forks and changes how the html elements are rendered in the back-end and doesn't update the js.

**Comment by Edwin-F** [comment]
@vkoves I am back. I updated the code based on your feedback.  Let me know if there are other suggestions. Thanks.

**Comment by vkoves** [comment]
@Edwin-F - thanks for the changes, these look great! My one request: can you add block comments describing what your functions do and what their parameters are? Just looking at `function sortLineDom(parentSelector, childSelectorCompare, id=0)` for instance, it's really hard for me to understand what I should pass in to each parameter to get the function to do what I want.

**Comment by AcademyInPeril** [comment]
@vkoves's review is stale, so after a period of testing this should be able to be merged.

**Comment by vkoves** [comment]
I've been sitting on this for a while, but overall I don't think a javascript solution fits with the way this project is headed right now, where we have everything in RoR unless absolutely needed otherwise. Also, this would not work if later on we needed to paginate lines or do anything like that where not all lines were returned client-side. Apologies, but thank you for the great work.

**Pull request closed without merging**
