### PR TITLE
closes #50

### LINKED ISSUE #50: Reconsider Favoriting Stops Redirecting to Favorites
Favoriting a stop redirects you to the favorites page, which takes you away from any page you might have been on. Favoriting should probably fire an AJAX request instead or at worst refresh the current page.

Original report from UX review last week:
> When clicking on the Favorite button, it automatically takes me to the Favorites page (which I don't necessarily want).

### PR DESCRIPTION
**Pull request by walshification**
closes https://github.com/CaravanTransit/Caravan-App/issues/50

Implements AJAX requests for favoriting and unfavoriting actions.

### Description of Changes:
* converts the favorites `new` and `delete` actions to be asynchronous
* adds `new.js.erb` and `delete.js.erb` views to swap view partials as a result of the async actions
* creates an `html_safe_id` on the `Stop` model so the stop ID can be used as a valid HTML ID

### Tests Added:
* favorites controller tests
* stop model test for `html_safe_id`

#### Reference Related Issue(s) or Spec Requirement:
- #50 

#### Checklist:
- [X] Code follows code style of this project
- [x] Tests added to cover changes
- [x] All new and existing tests passing
#

### CODE REVIEW

**Comment by walshification** [comment]
I wanted to put something up so you can see the progress I've made. Tests to come tomorrow night!

**Comment by walshification** [comment]
Tests added; build passing, @vkoves!

**Comment by vkoves** [comment]
@walshification - this looks great! My two questions/requests:

1) Can you add documentation explaining what your `js.erb` files do and the partials they use? That would make it clear so that if folks need/want to change either, they know what to keep in mind
2) What would be the best way to handle errors if the async favoriting call works? I emulated being offline in Chrome ([reference](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#offline)) and clicking the favorites buttons didn't do anything (to be expected), but I think we should show an error if it's possible. That might be outside of the scope of this task, so making a new issue to address this would be sufficient

**Comment by walshification** [comment]
@vkoves, sure thing. Do you want a `docs` section dedicated to it or inline comments explaining? I haven't worked much with the errors you bring up in #2, but I'm intrigued. I'll be around tonight if you could chat more about it.

**Comment by vkoves** [comment]
@walshification - inline comments would be perfect, thanks!

**Comment by AcademyInPeril** [comment]
@vkoves, did you happen to see these changes? Is there anything still holding up a merge?

**Comment by vkoves** [comment]
Nope, this looks good!

**Pull request merged**
